create table if not exists hit
(

    id           bigint generated by default as identity
    primary key,
    story_id     bigint,
    author       varchar(255),
    month        varchar(255),
    title        varchar(255),
    data         jsonb,
    hidden       boolean,
    created_date timestamp(6)
    );

create table if not exists request
(

    id           bigint generated by default as identity
    primary key,
    data         jsonb,
    created_date timestamp(6)
    );

create table if not exists user_entity
(
    id          bigint generated by default as identity
    primary key,
    username    varchar(255),
    password    varchar(255),
    role        varchar(255)
    );


